# Site settings
title: Alec M. Chiu
email: 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "alecmchiu.github.io" # the base hostname & protocol for your site
github_username: alecmchiu

# Build settings
markdown: kramdown

kramdown:
 input: GFM
